# Generated by Django 3.2.15 on 2022-11-24 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='user',
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='fert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='plaant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seed',
            name='seeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nursery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
